database:
  sock: /tmp/.s.PGSQL.5432
  user: dylan
  db: dylan
settings:
  enable-caret-browsing: True
  enable-developer-extras: True
  enable-fullscreen: False
  enable-html5-database: False
  enable-html5-local-storage: False
  enable-java: False
  enable-offline-web-application-cache: False
  enable-plugins: False
  enable-write-console-messages-to-stdout: True
  hardware-acceleration-policy: 2 # never
  media-playback-requires-user-gesture: True
  zoom-text-only: False
style-sheet: "plain.css"
cookie-accept-policy: false
allow-load: false
