database:
  sock: /tmp/.s.PGSQL.5432
  user: dylan
  db: dylan
settings:
  enable-caret-browsing: True
  enable-developer-extras: True
  enable-fullscreen: False
  enable-html5-database: False
  enable-html5-local-storage: False
  enable-java: False
  enable-offline-web-application-cache: False
  enable-plugins: False
  enable-write-console-messages-to-stdout: True
  hardware-acceleration-policy: 2 # never
  media-playback-requires-user-gesture: True
  zoom-text-only: True
style-sheet: "plain.css"
user-agent:
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537 (KHTML, like Gecko) Chrome/40 Safari/537"
  - "Mozilla/5.0 (X11; Linux x86_64) Gecko/20180101 Firefox/45.0"
  - "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/5.0)"
cookie-accept-policy: false
block-load:
  - SCRIPT
  - IFRAME
block-load-src:
  - adnxs.com
  - amazon-adsystem.com
  - as5000.com
  - atdmt.com
  - dwoozone.com
  - google-analytics.com
  - googlesyndication.com
  - mediaplex.com
  - optimizely.com
  - quantserve.com
  - scorecardresearch.com
  - sharingmachine.com
  - webtrendslive.com
  - 2mdn.net
  - crwdcntrl.net
  - doubleclick.net
  - facebook.net
  - thebrighttag.com
