database:
  sock: /tmp/.s.PGSQL.5432
  user: dylan
  db: dylan
settings:
  enable-caret-browsing: True
  enable-developer-extras: True
  enable-fullscreen: False
  enable-html5-database: False
  enable-html5-local-storage: False
  enable-java: False
  enable-offline-web-application-cache: False
  enable-plugins: False
  enable-write-console-messages-to-stdout: True
  hardware-acceleration-policy: 2 # never
  media-playback-requires-user-gesture: True
  zoom-text-only: True
style-sheet: "plain.css"
user-agent:
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537 (KHTML, like Gecko) Chrome/40 Safari/537"
  - "Mozilla/5.0 (X11; Linux x86_64) Gecko/20180101 Firefox/45.0"
  - "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/5.0)"
cookie-accept-policy: false
allow-load:
  "": [IMG, LINK]
  adnxs.com: []
  amazon-adsystem.com: []
  as5000.com: []
  atdmt.com: []
  dwoozone.com: []
  google-analytics.com: []
  googlesyndication.com: []
  mediaplex.com: []
  optimizely.com: []
  quantserve.com: []
  scorecardresearch.com: []
  sharingmachine.com: []
  webtrendslive.com: []
  2mdn.net: []
  crwdcntrl.net: []
  doubleclick.net: []
  facebook.net: []
  thebrighttag.com: []
  appdynamics.com: []
  twitter.com: []
  github.com: true
  maps.google.com: true
site:
  github.com:
    cookie-accept-policy: true
  travis-ci.org:
    allow-load:
      travis-ci.org: true
  bikes.oobrien.com:
    allow-load: true
uri-rewrite:
  amg: https://www.allmusic.com/search/artist/
  dd: https://duckduckgo.com/html/?kp=-1&kd=-1&q=
  "": https://duckduckgo.com/html/?kp=-1&kd=-1&q=
  dict: https://dictionary.reference.com/search?q=
  g: https://www.google.com/search?q=
  gi: https://www.google.com/search?tbm=isch&q=
  gm: https://maps.google.com/maps?q=
  gn: https://news.google.com/news?q=
  gs: https://scholar.google.com/scholar?q=
  hdb: https://hackage.haskell.org/package/
  hoogle: https://haskell.org/hoogle/?q=
  imdb: https://imdb.com/find?q=
  math: https://mathworld.wolfram.com/search/?query=
  netflix: https://www.netflix.com/Search?v1=
  om: https://openstreetmap.org/?query=
  rfc: https://tools.ietf.org/html/rfc
  thes: https://thesaurus.reference.com/search?q=
  trackdhl: https://track.dhl-usa.com/TrackByNbr.asp?ShipmentNumber=
  trackfedex: https://www.fedex.com/cgi-bin/tracking?action=track&language=english&last_action=alttrack&ascend_header=1&cntry_code=us&initial=x&mps=y&tracknumbers=
  trackups: https://wwwapps.ups.com/etracking/tracking.cgi?TypeOfInquiryNumber=T&track.x=0&track.y=0&InquiryNumber1=
  trackusps: https://trkcnfrm1.smi.usps.com/PTSInternetWeb/InterLabelInquiry.do?origTrackNum=
  urban: https://www.urbandictionary.com/define.php?term=
  weather: https://classic.wunderground.com/cgi-bin/findweather/getForecast?query=
  wiki: https://www.wikipedia.org/w/wiki.phtml?search=
uri-alias:
  amg: https://www.allmusic.com/
  gc: https://google.com/calendar
  gm: https://maps.google.com/
  hdb: https://hackage.haskell.org/packages
  imdb: https://imdb.com/
  math: https://mathworld.wolfram.com/
  om: https://openstreetmap.org/
  radar: https://classic.wunderground.com/radar/radblast.asp?num=10&delay=50&noclutter=0&ID=JFK&type=TR0&showstorms=0&lightning=0&showlabels=0&rainsnow=1
