resolver: lts-9.21
packages:
- .
extra-deps:
- gi-webkit2-4.0.15
- gi-gdk-3.0.15
- gi-gio-2.0.17
- gi-gtk-3.0.22
- gi-soup-2.4.15
- gi-gdkpixbuf-2.0.15
- gi-pango-1.0.16
# in lts-11:
- gi-javascriptcore-4.0.15
- haskell-gi-0.21.0
- haskell-gi-base-0.21.0
build:
  #haddock: true
